# These are supported funding model platforms

github: Unix-like-SoN

custom:
  - "Crypto: USDT BEP-20: 0x4f85f29892b261fa8029f3cfd64211e166744733"
  - "Crypto: USDT TRC-20: TDnjDg9HxySo1J2FPSrvWQejyZ4gHKiXSJ"
